name: تجربه‌های کاری
url: https://tajrobe.github.io
baseurl: /
permalink: /:title/
paginate_path: /page/:num/
paginate: 200
disqus:
github: https://github.com/tajrobe/tajrobe.github.io/
reviewActionUrl: https://creepy-seal-zipper.cyclic.cloud
google_analytics:
webmaster_verifications:
  google: 
defaults:
  - scope:
      path: assets/*
    values:
      sitemap: false 
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
plugins:
  - jekyll-sitemap
  - jekyll-feed 
  - jekyll-paginate
  - jekyll-seo-tag  
